version: "3"

services:
  nest-server:
    image: docker-registry.ebrains.eu/nest/nest-simulator:3.4-rc1
    environment:
      NEST_CONTAINER_MODE: "nest-server"
      NEST_SERVER_BUFFER_SIZE: 65535
      NEST_SERVER_HOST: "0.0.0.0"
      NEST_SERVER_MODULES: "nest,numpy"
      NEST_SERVER_PORT: 5000
      NEST_SERVER_RESTRICTION_OFF: 1
      NEST_SERVER_STDOUT: 1
    ports:
      - "5000:5000"

  nest-desktop:
    image: docker-registry.ebrains.eu/nest/nest-simulator:3.4-rc1
    environment:
      LOCAL_USER_ID: "`id -u $USER`"
      NEST_CONTAINER_MODE: "nest-desktop"
    ports:
      - "8000:8000"
    depends_on:
      - nest-server

  nest-notebook:
    image: docker-registry.ebrains.eu/nest/nest-simulator:3.4-rc1
    volumes:
      - .:/opt/data
    environment:
      LOCAL_USER_ID: "`id -u $USER`"
      NEST_CONTAINER_MODE: "notebook"
    ports:
      - "8080:8080"

  nest-jupyterlab:
    image: docker-registry.ebrains.eu/nest/nest-simulator:3.4-rc1
    volumes:
      - .:/opt/data
    environment:
      LOCAL_USER_ID: "`id -u $USER`"
      NEST_CONTAINER_MODE: "jupyterlab"
    ports:
      - "8080:8080"
