version: "3"

services:
  nest-server:
    image: docker-registry.ebrains.eu/nest/nest-simulator:dev
    environment:
      LOCAL_USER_ID: "`id -u $USER`"
      NEST_CONTAINER_MODE: "nest-server"
    ports:
      - "52425:52425"

  nest-desktop:
    image: docker-registry.ebrains.eu/nest/nest-simulator:dev
    environment:
      LOCAL_USER_ID: "`id -u $USER`"
      NEST_CONTAINER_MODE: "nest-desktop"
    ports:
      - "8000:8000"
    depends_on:
      - nest-server

  nest-notebook:
    image: docker-registry.ebrains.eu/nest/nest-simulator:dev
    volumes:
      - .:/opt/data
    environment:
      LOCAL_USER_ID: "`id -u $USER`"
      NEST_CONTAINER_MODE: "notebook"
    ports:
      - "8080:8080"

  nest-jupyterlab:
    image: docker-registry.ebrains.eu/nest/nest-simulator:dev
    volumes:
      - .:/opt/data
    environment:
      LOCAL_USER_ID: "`id -u $USER`"
      NEST_CONTAINER_MODE: "jupyterlab"
    ports:
      - "8080:8080"
