###############################################
###               v3.6                     ###
###############################################

Build_36:
  stage: build
  needs: ["Build_Base"]
  rules:
    - when: always
  script:
    # Build
    - docker pull nest/nest-simulator:3.6 || true
    - docker build
        --cache-from nest/nest-simulator:3.6
        --tag nest/nest-simulator:3.6
        ./src/3.6
    # Test
    - docker run -i --rm nest/nest-simulator:3.6 bash /opt/test-nest.sh
    # Deploy
    - echo -n $DOCKERHUB_REGISTRY_TOKEN | docker login -u $DOCKERHUB_REGISTRY_USER --password-stdin
    - docker push nest/nest-simulator:3.6
    - docker tag nest/nest-simulator:3.6 $DOCKER_REGISTRY_IMAGE:3.6
    - docker push $DOCKER_REGISTRY_IMAGE:3.6  
    - docker logout $DOCKERHUB_REGISTRY
    - docker logout $DOCKER_REGISTRY
  tags:
    - shell-runner

