###############################################
###               3.7rc1                   ###
###############################################

Build_Dev:
  stage: build
  rules:
    - when: always
  script:
    # Build
    - docker pull push nest/nest-simulator:3.7rc1 || true
    - docker build
        --cache-from nest/nest-simulator:3.7rc1
        --tag nest/nest-simulator:3.7rc1
        ./src/3.7rc1
    # Test
    - docker run -i --rm nest/nest-simulator:3.7rc1 bash /opt/test-nest.sh
    # Deploy
    - echo -n $DOCKERHUB_REGISTRY_TOKEN | docker login -u $DOCKERHUB_REGISTRY_USER --password-stdin
    - docker push nest/nest-simulator:3.7rc1
    - docker logout $DOCKERHUB_REGISTRY
  tags:
    - shell-runner

