###############################################
###               3.9                  ###
###############################################


Build_3.9:
  stage: build
  rules:
    - when: always
  script:
    # Build
    - docker pull nest/nest-simulator:3.9-rc1 || true
    - docker build
        --cache-from nest/nest-simulator:3.9-rc1
        --tag nest/nest-simulator:3.9-rc1
        --tag nest/nest-simulator:latest
        ./src/3.9
    # Test
    #- docker run -i --rm nest/nest-simulator:3.8bash /opt/test-nest.sh
    # Deploy
    - echo -n $DOCKERHUB_REGISTRY_TOKEN | docker login -u $DOCKERHUB_REGISTRY_USER --password-stdin
    - docker push nest/nest-simulator:3.9-rc1
    - docker logout $DOCKERHUB_REGISTRY
  tags:
    - shell-runner

