FROM buildpack-deps:jammy as builder
LABEL maintainer="s.graber@fz-juelich.de"

ENV TERM=xterm \
    TZ=Europe/Berlin \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libtool automake autotools-dev libreadline8 libreadline-dev freeglut3-dev \
    ccache \
    gosu \
    cmake \
    cython3 \
    jq \
    libboost-dev \
    libgomp1 \
    libgsl-dev \
    libhdf5-dev \
    libltdl7 \
    libltdl-dev \
    libmusic1v5 \
    libncurses-dev \
    libopenmpi-dev \
    libomp-dev \
    libpcre3 \
    libpcre3-dev \
    libpython3.10 \
    libreadline-dev \
    libzmq3-dev \
    llvm-dev \
    openmpi-bin \
    pep8 \
    python3-dev \
    python3-h5py \
    python3-ipython \
    python3-jupyter-core \
    python3-matplotlib \
    python3-mpi4py \
    python3-nose \
    python3-numpy \
    python3-pandas \
    python3-path \
    python3-pip \
    python3-scipy \
    python3-setuptools \
    python3-sphinx \
    python3-statsmodels \
    python3-tk \
    tcl8.6 tcl8.6-dev tk8.6-dev \
    vera++ \
    wget && \
    # update-alternatives --remove-all python && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3 10 && \
    update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10 && \
    python3 -m pip install --upgrade pip setuptools wheel mock pandoc


# Install music
RUN cd . && wget https://github.com/INCF/MUSIC/archive/master.tar.gz && \
    gunzip < master.tar.gz | tar xf -  && \
    rm -f master.tar.gz && \
    cd MUSIC-master && \
    sh ./autogen.sh && \
    ./configure --prefix=/opt/music-install && \
    make && \
    make install

# Install HDF5
# RUN cd . && rm -f hdf5-1_12_2.tar.gz && wget https://github.com/HDFGroup/hdf5/archive/refs/tags/hdf5-1_12_2.tar.gz  && \
#    gunzip < hdf5-1_12_2.tar.gz | tar xf -  && \
#    rm -f hdf5-1_12_2..tar.gz && cd hdf5-hdf5-1_12_2 && \
#    ./configure --prefix=/opt/hdf5 --enable-cxx && \
#    make  && \
#    make install 
