FROM ubuntu:jammy
LABEL maintainer="s.graber@fz-juelich.de"

ENV TERM=xterm \
    TZ=Europe/Berlin \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt autoremove && apt autoclean && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        curl \
        libpcre3 \
        libpcre3-dev \
        libboost-dev \
        gosu \
        less \
        libgomp1 \
        libgsl-dev  \
        libltdl7 \
        libncurses-dev \
        libopenmpi-dev \
        libomp-dev \
        libpython3-dev \
        libreadline-dev \
        nano \
        openmpi-bin \
        openssh-client \
        openssh-server \
        python3-dev \
        python3-flask \
        python3-flask-cors \
        python3-restrictedpython \
        python3-matplotlib \
        python3-mpi4py \
        python3-numpy \
        python3-pip \
        python3-scipy \
        python3-setuptools \
        python3-tqdm \
        python3-pandas \
        python3-sympy \
        python3-tk \
        uwsgi \
        wget && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3 10 && \
    update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10 && \
    python3 -m pip install jupyter notebook && \
    python3 -m pip install quantities lazyarray neo && \
    python3 -m pip install --no-binary :all: PyNN && \
    python3 -m pip install Flask --upgrade && \
    python3 -m pip install Flask-cors --upgrade && \
    python3 -m pip install RestrictedPython --upgrade && \
    python3 -m pip install nest-desktop && \
    python3 -m pip install MarkupSafe==2.0.1 && \
    python3 -m pip install gunicorn && \
    python3 -m pip install jupyterlab && \
    python3 -m pip install elephant[extras] && \
    python3 -m pip install MarkupSafe==2.0.1 && \ 
    python3 -m pip install nestml --pre
